### ISSUE TITLE
how to integrate with angular 4 and polymer 2.0 project

### ISSUE THREAD

**Issue by nishantgirbar** [ag-grid/ag-grid-polymer-example#1]
Hi,

I was trying to use ag-grid-polymer into one project which is called Origami built with angular 4+ Polymer 2.0. But it is giving issues as below.
ERROR in ../src/assets/bower_components/ag-grid/src/ts/rendering/cellComp.ts (666,9): Type 'IComponent, IAfter
GuiAttachedParams' is not assignable to type 'ICellRendererComp'.

Please help me to sort out this.

**Comment by seanlandsman** [comment]
I'm afraid I dont think we'll be able to assist you with this - combining the two is not something we've tried yet.

The above however doesn't sound like a angular/polymer issue, but rather a typescrit one
